version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: e_commerce
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=e_commerce
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prisma-networks

networks:
  prisma-networks:
    driver: bridge

volumes:
  postgres_data:
